### ISSUE TITLE
Axiom this server supports Axiom, but your client does not.

### ISSUE THREAD

**Issue by pLexiGlass01** [Moulberry/AxiomClientAPI#1]
![image](https://github.com/Moulberry/AxiomClientAPI/assets/136620633/d426e57c-9815-4f67-80ca-76588da1e576)
This is weird as i have it installed on both the client and server side. I am using 1.20.1 fabric, using the modrinth launcher. Pls help

**Comment by HalfDeadHawkes** [comment]
Ok, basically you need to get your client authorized to work on multiplayer by going into the discord and applying to be whitelisted. That should work. They respond pretty quickly and are good about getting you authorized. but you need to get your minecraft UUID for it which can be found easily. Hope this helped!
